-- Replace single is_pr with explicit PR flags + stored est 1RM
alter table public.workout_sets drop column if exists is_pr;
alter table public.workout_sets add column is_weight_pr boolean not null default false;
alter table public.workout_sets add column is_1rm_pr boolean not null default false;
alter table public.workout_sets add column est_1rm numeric;

-- Curated starter exercise library (shared: is_custom=false, owner_id=null)
insert into public.exercises (name, muscle_group, type, is_custom) values
('Barbell Bench Press','chest','barbell',false),
('Incline Barbell Bench Press','chest','barbell',false),
('Dumbbell Bench Press','chest','dumbbell',false),
('Incline Dumbbell Press','chest','dumbbell',false),
('Cable Fly','chest','cable',false),
('Push-Up','chest','bodyweight',false),
('Overhead Press','shoulders','barbell',false),
('Dumbbell Shoulder Press','shoulders','dumbbell',false),
('Lateral Raise','shoulders','dumbbell',false),
('Rear Delt Fly','shoulders','dumbbell',false),
('Face Pull','shoulders','cable',false),
('Barbell Back Squat','legs','barbell',false),
('Front Squat','legs','barbell',false),
('Leg Press','legs','machine',false),
('Romanian Deadlift','legs','barbell',false),
('Leg Extension','legs','machine',false),
('Leg Curl','legs','machine',false),
('Walking Lunge','legs','dumbbell',false),
('Standing Calf Raise','legs','machine',false),
('Conventional Deadlift','back','barbell',false),
('Barbell Row','back','barbell',false),
('Pull-Up','back','bodyweight',false),
('Lat Pulldown','back','cable',false),
('Seated Cable Row','back','cable',false),
('Dumbbell Row','back','dumbbell',false),
('Barbell Curl','arms','barbell',false),
('Dumbbell Curl','arms','dumbbell',false),
('Hammer Curl','arms','dumbbell',false),
('Preacher Curl','arms','machine',false),
('Cable Triceps Pushdown','arms','cable',false),
('Overhead Triceps Extension','arms','dumbbell',false),
('Close-Grip Bench Press','arms','barbell',false),
('Dips','arms','bodyweight',false),
('Plank','core','bodyweight',false),
('Hanging Leg Raise','core','bodyweight',false),
('Cable Crunch','core','cable',false),
('Russian Twist','core','bodyweight',false),
('Back Extension','core','bodyweight',false),
('Goblet Squat','legs','dumbbell',false),
('Hip Thrust','legs','barbell',false),
('Incline Dumbbell Curl','arms','dumbbell',false),
('Machine Chest Press','chest','machine',false),
('Pec Deck','chest','machine',false),
('Arnold Press','shoulders','dumbbell',false),
('Cable Lateral Raise','shoulders','cable',false),
('Hack Squat','legs','machine',false),
('Seated Leg Curl','legs','machine',false),
('T-Bar Row','back','barbell',false),
('Chin-Up','back','bodyweight',false),
('Skullcrusher','arms','barbell',false)
on conflict do nothing;
